### ISSUE TITLE
Задания 2

### ISSUE THREAD

**Issue by Vyacheslav-TKI** [Vyacheslav-TKI/Subutai#6]
Соответственно выполняю 11 номера из заданий 2
[Задание 2-1  (1).docx](https://github.com/I461-TKI/Subutai/files/12599898/2-1.1.docx)
[Задание 2-2 .docx](https://github.com/I461-TKI/Subutai/files/12599899/2-2.docx)
[Задание 2-3 .docx](https://github.com/I461-TKI/Subutai/files/12599900/2-3.docx)

**Comment by MarinaPaley** [comment]
@I461-TKI Не удобно пользоваться Вашим `issue`. Приложите, пожалуйста, картинку (скрин). Word здесь не открывается

**Comment by Vyacheslav-TKI** [comment]
2-1: 
![2-1](https://github.com/I461-TKI/Subutai/assets/61204893/a7cd151d-4b71-447c-8b90-12607cbda983)

**Comment by Vyacheslav-TKI** [comment]
2-2: 
![2-2](https://github.com/I461-TKI/Subutai/assets/61204893/2ca22211-800e-4e82-9e01-dd131b1ec0dd)

**Comment by Vyacheslav-TKI** [comment]
2-3: 
![2-3](https://github.com/I461-TKI/Subutai/assets/61204893/6cb8ce7c-d855-4ce9-9d6d-afbad113e7ac)

**Comment by Vyacheslav-TKI** [comment]
@MarinaPaley Исправлено. Я так же вставил скриншоты и в issue помеченные "Задание 1"

**Comment by Vyacheslav-TKI** [comment]
# Задание 2-1 (Вариант 11) 

![task-2-1](https://github.com/I461-TKI/Subutai/assets/61204893/a7cd151d-4b71-447c-8b90-12607cbda983)

```c
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <stdbool.h>


/**
 * @brief Функция проверяет, положительное ли число?
 * @param x проверяемое число
 * @return 1 - число положительное и отличное от нуля, 0 - число отрицательное или нуль
*/
int is_positive(const double x);

/**
 * @brief Функция вычисляет нужную пользователю искомую величину
 * @param x порядковый номер формулы
*/
double formula_selection(int x, double cube_edge);

/**
 * @brief Функция сверяет введенное значение из переменной formula
 * @param x значение переменной  formula
 * @return 1 - введенное число принадлежит диапазону [1;3]
 */
int is_right_number(const int x);

enum Values
{
    face_area = 1,
    total_surface = 2,
    volume = 3,
};

int main(){

    double cube_edge;
    int formula;
    puts("Please, insert a non-negative number\n");

    if(scanf("%lf", &cube_edge) != 1){
        puts("Please insert a valid value\n");
        abort();}
    if (is_positive(cube_edge) == 0){
        puts("Please, enter a non-negative number!\n");
        abort();
    }

    puts("Please, write what you want to find: face area, total surface area or volume\n");
    puts("If you want to find face area, press '1'.\n");
    puts("If you want to find total surface, press '2'\n");
    puts("If you want to find volume, press '3'\n");

    if(scanf("%d", &formula) != 1){
        puts("Please input a valid value!\n");
        abort();}
    if(is_right_number(formula) == 0){
        puts("Please, enter 1, 2 or 3!\n");
        abort();
    }
    else{
        formula_selection(formula, cube_edge);
    }
    return 0;
}


int is_right_number(const int x){
    if(x > 0 && x < 4){
        return 1;
    }
    return 0;
}

int is_positive(const double x){
    if(x>0){
        return 1;
    }
    return 0;
}

double formula_selection(int x, double cube_edge){
    enum Values face = face_area, total = total_surface, volume_cube = volume;
    if(x == face){
            double x = cube_edge*cube_edge;
            printf("Face area equals: %lf", x);
        }
        else if(x == total){
            double y = 6 * cube_edge * cube_edge;
            printf("Total surface equals: %lf", y);
        }
        else if(x == volume_cube){
            double z = cube_edge*cube_edge*cube_edge;
            printf("Volume equals: %lf", z);
        }
}
```

**Comment by Vyacheslav-TKI** [comment]
# Задание 2-2 (Вариант 11)

![task-2-2](https://github.com/I461-TKI/Subutai/assets/61204893/2ca22211-800e-4e82-9e01-dd131b1ec0dd)

```c
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/**
 * @brief Функция вычисляет первое(верхнее уравнение)
 * @param a Заданная константа
 * @param x Заданная пользователем переменная
*/
double upper_equation(double a, double x);

/**
 * @brief Функция вычисляет второе(нижнее) уравнение
 * @param a Заданная константа
 * @param x Заданная пользователем переменная
*/
double lower_equation(double a, double x);

int main(){

    double a = 0.3f;
    double x;
    double y;
    double result;
    puts("Enter value of x\n");
    if(scanf("%lf", &x) != 1){
        puts("Please insert a valid value\n");
        abort();}

    if(a*x < 1){
        result = upper_equation(a, x);
        printf("X equals: %lf", result);
    }
    else if(a*x >= 1){
        result = lower_equation(a, x);
        printf("X equals: %lf", result);
    }

    return 0;
}

double upper_equation(double a, double x){
    return a * sin((x*x+1)/10);
}

double lower_equation(double a, double x){
    return a * cos((x-1)/10);
}
```

**Comment by Vyacheslav-TKI** [comment]
2-2 final
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/**
*    @brief Функция вычисляет первое(верхнее уравнение)
*    @param a Заданная константа
*    @param x Заданная пользователем переменная
*/
double upper_equation(double a, double x);

/**
*    @brief Функция вычисляет второе(нижнее) уравнение
*    @param a Заданная константа
*    @param x Заданная пользователем переменная
*/
double lower_equation(double a, double x);

int main(){

    double a = 0.3f;
    double x;
    double y;
    double result;
    puts("Enter value of x\n");
    if(scanf("%lf", &x) != 1){
        puts("Please insert a valid value\n");
        abort();}

    if(a*x < 1){
        result = upper_equation(a, x);
        printf("X equals: %lf", result);
    }
    else{
        result = lower_equation(a, x);
        printf("X equals: %lf", result);
    }

    return 0;

}

double upper_equation(double a, double x){
    return a * sin((x*x+1)/10);
}

double lower_equation(double a, double x){
    return a * cos((x-1)/10);
}

**Comment by Vyacheslav-TKI** [comment]
2-1 pre-final
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <stdbool.h>

/**
*    @brief Функция проверяет, положительное ли число?
*    @param x проверяемое число
*    @return 1 - число положительное и отличное от нуля, 0 - число отрицательное или нуль
*/
int is_positive(const double x);

/**
*    @brief Функция вычисляет нужную пользователю искомую величину
*    @param x порядковый номер формулы
*/
double formula_selection(int x, double cube_edge);

/**
*    @brief Функция сверяет введенное значение из переменной formula
*    @param x значение переменной formula
*    @return 1 - введенное число принадлежит диапазону [1;3]
*/
int is_right_number(const int x);

enum Values
{
    face_area = 1,
    total_surface = 25,
    volume = 3,
};

int main(){

    double cube_edge;
    int formula;
    puts("Please, insert a non-negative number\n");

    if(scanf("%lf", &cube_edge) != 1){
        puts("Please insert a valid value\n");
        abort();}
    if (is_positive(cube_edge) == 0){
        puts("Please, enter a non-negative number!\n");
        abort();
    }

    puts("Please, write what you want to find: face area, total surface area or volume\n");
    printf("If you want to find face area, press %d\n", (enum Values)(face_area));
    puts("If you want to find total surface, press '2'\n");
    puts("If you want to find volume, press '3'\n");
 
   

    if(scanf("%d", &formula) != 1){
        puts("Please input a valid value!\n");
        abort();}
    if(is_right_number(formula) == 0){
        puts("Please, enter 1, 2 or 3!\n");
        abort();
    }
    else{
        formula_selection(formula, cube_edge);
    }
    return 0;

}

int is_right_number(const int x){
    if(x > 0 && x < 4){
        return 1;
    }
    return 0;
}

int is_positive(const double x){
    if(x>0){
    return 1;
    }
    return 0;
}

double formula_selection(int x, double cube_edge){
    enum Values face = face_area, total = total_surface, volume_cube = volume;
    if(x == face){
        double x = cube_edge*cube_edge;
        printf("Face area equals: %lf", x);
    }
    else if(x == total){
        double y = 6 * cube_edge * cube_edge;
        printf("Total surface equals: %lf", y);
    }
    else if(x == volume_cube){
        double z = cube_edge*cube_edge*cube_edge;
        printf("Volume equals: %lf", z);
    }
}

**Comment by Vyacheslav-TKI** [comment]
2-1 с нюансом
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <stdbool.h>

/**
*@brief Функция проверяет, положительное ли число?
*@param x проверяемое число
*@return 1 - число положительное и отличное от нуля, 0 - число отрицательное или нуль
*/
int is_positive(const double x);
/**
*@brief Функция вычисляет нужную пользователю искомую величину
*@param x порядковый номер формулы
*/
double formula_selection(int x, double cube_edge);
/**
*@brief Функция сверяет введенное значение из переменной formula
*@param x значение переменной formula
*@return 1 - введенное число принадлежит диапазону [1;3]
*/
int is_right_number(const int x);

enum Values
{
    face_area = 1,
    total_surface = 2,
    volume = 3,
};
/**
 * @brief Точка входа в программу
 * @return 0 программа работает правильно
 * @return 1 в программе есть ошибка
*/
int main(){

    double cube_edge;
    int formula;
    puts("Please, insert a non-negative number\n");

    if(scanf("%lf", &cube_edge) != 1){
        puts("Please insert a valid value\n");
        return 1;}
        if (is_positive(cube_edge) == 0){
        puts("Please, enter a non-negative number!\n");
        return 1;
    }

    puts("Please, write what you want to find: face area, total surface area or volume\n");
    printf("If you want to find face area, press %d\n", (enum Values)(face_area));
    printf("If you want to find total surface, press %d\n", (enum Values)(total_surface));
    printf("If you want to find volume, press %d\n", (enum Values)(volume));
    
    if(scanf("%d", &formula) != 1){
        puts("Please input a valid value!\n");
        return 1;}
    if(is_right_number(formula) == 0){
        printf("Please, enter %d, %d or %d!\n", (enum Values)(face_area), (enum Values)(total_surface), (enum Values)(volume));
        return 1;
    }
    else{
        formula_selection(formula, cube_edge);
    }
        return 0;
}

int is_right_number(const int x){
    return (x > 0 && x < 4) ? 1 : 0;
}

int is_positive(const double x){ // Зачем мне тут использовать bool?
    if(x>0){
        return 1;
    }
    return 0;
}

double formula_selection(int x, double cube_edge){
    
    if(x == (enum Values)(face_area)){
        double x = cube_edge*cube_edge;
        printf("Face area equals: %lf", x);
    }
    else if(x == (enum Values)(total_surface)){
        double y = 6 * cube_edge * cube_edge;
        printf("Total surface equals: %lf", y);
    }
    else if(x == (enum Values)(volume)){
        double z = cube_edge*cube_edge*cube_edge;
        printf("Volume equals: %lf", z);
    }
}

**Comment by Vyacheslav-TKI** [comment]
2-2 с законченной документацией
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/**
 * @brief Функция вычисляет первое(верхнее уравнение)
 * @param a Заданная константа
 * @param x Заданная пользователем переменная
*/
double upper_equation(double a, double x);

/**
 * @brief Функция вычисляет второе(нижнее) уравнение
 * @param a Заданная константа
 * @param x Заданная пользователем переменная
*/
double lower_equation(double a, double x);


/**
 * @brief Точка входа в программу
 * @return 0 Программа исправна
 * @return 1 Программа неисправна
*/
int main(){
    double a = 0.3f;
    double x;
    double y;
    double result;
    puts("Enter value of x\n");
    if(scanf("%f", &x) != 1){
        puts("Please insert a valid value\n");
        abort();}

    if(a*x < 1){
        result = upper_equation(a, x);
        printf("X equals: %lf", result);
    }
    else{
        result = lower_equation(a, x);
        printf("X equals: %lf", result);
    }
        return 0;
}

double upper_equation(double a, double x){
    return a * sin((x*x+1)/10);
}

double lower_equation(double a, double x){
    return a * cos((x-1)/10);
}

**Comment by Vyacheslav-TKI** [comment]
2-3
#include <stdio.h>
#include <math.h>
#include <stdlib.h>

/** 
 * @brief Функция проверяет положительность числа
 * @param x проверяемое число
 * @return 1 - число отрицательное или равное нулю, 0 - число положительное
*/
int pozitive_num(double x);

/**
 * @brief Функция проверяет принадлежность задданного значения к положительным числам
 * @return x введенное правильное значение
*/
double get_number();

/**
 * @brief Функция проверяет, можно ли из этих сторон построить треугольник
 * @param first_side длина отрезка
 * @param second_side длина отрезка
 * @param third_side длина отрезка
 * @return 1 можно построить треугольник
 * @return 0 нельзя построить треугольник
*/
int is_triangle(double first_side, double second_side, double third_side);

/**
 * @brief Функция проверяет треугольник на остроугольность по его сторонам
 * @param first_side длина стороны
 * @param second_side длина стороны
 * @param third_side длина стороны
 *  @return 1 Треугольник остроугольный
 * @return 0 Треугольник не остроугольный
*/
int is_acute(double first_side, double second_side, double third_side);

/**
 * @brief Точка входа в программу
*/
int main(){
    puts("In the next(3) strings enter non-negative numbers\n");

    double first_side = get_number(), second_side = get_number(), third_side = get_number();
    
    if(is_triangle(first_side, second_side, third_side) == 0){
        puts("It is impossible to make a triangle from these sides\n");
    }
    else{
        puts("It is possible to make a triangle from these sides\n");
        if(is_acute(first_side, second_side, third_side) == 1){
            puts("Acute triangle\n");
        }
        else{
            puts("Non-acute triangle\n");
        }
    }
    return 0;
}

int pozitive_num(double x){
    return x > 0 ? 0 : 1;
}

double get_number(){
    double x;
    if(scanf("%lf", &x) != 1){
        puts("Please insert a valid value\n");
        abort();}
    if(pozitive_num(x) == 1){
        puts("Please, enter non-negative number\n");
        abort();
    }
    return x;
}

int is_triangle(double first_side, double second_side, double third_side){
    if((first_side+second_side > third_side) && (first_side + third_side > second_side) && (second_side+third_side > first_side)){
        return 1;}
    return 0;
}

int is_acute(double first_side, double second_side, double third_side){
    if((first_side*first_side < second_side*second_side+third_side*third_side) && (second_side*second_side < first_side*first_side+third_side*third_side) && (third_side*third_side < first_side*first_side+second_side*second_side)){
        return 1;}
    return 0;
}

**Comment by MarinaPaley** [comment]
@Vyacheslav-TKI, я как могла, подправила Ваши комментарии (_не все_), но суть от этого не меняется! Вы НЕПРАВИЛЬНО пользуетесь инструментом (#10)! Комментарии нужны для обсуждения маленьких локальных вопросов в рамках постановки технического задания / формализации задачи. Особенности её решения / реализации кода обсуждаются в рамках рецензирования созданного запроса на внесение изменений (review PR).
